In [1]:
import pandas as pd

In [2]:
train_data = pd.read_csv('C:/Users/Satellite/Documents/1.DATA SCIENCE/KAGGLE/House Prices/train.csv')
train_data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
train_data.drop(columns='Id', inplace=True)
train_data.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

## Checking for missing values in the data

In [4]:
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 80 columns):
MSSubClass       1460 non-null int64
MSZoning         1460 non-null object
LotFrontage      1201 non-null float64
LotArea          1460 non-null int64
Street           1460 non-null object
Alley            91 non-null object
LotShape         1460 non-null object
LandContour      1460 non-null object
Utilities        1460 non-null object
LotConfig        1460 non-null object
LandSlope        1460 non-null object
Neighborhood     1460 non-null object
Condition1       1460 non-null object
Condition2       1460 non-null object
BldgType         1460 non-null object
HouseStyle       1460 non-null object
OverallQual      1460 non-null int64
OverallCond      1460 non-null int64
YearBuilt        1460 non-null int64
YearRemodAdd     1460 non-null int64
RoofStyle        1460 non-null object
RoofMatl         1460 non-null object
Exterior1st      1460 non-null object
Exterior2nd      1460 non-null object
MasVnrType       1452 non-null object
MasVnrArea       1452 non-null float64
ExterQual        1460 non-null object
ExterCond        1460 non-null object
Foundation       1460 non-null object
BsmtQual         1423 non-null object
BsmtCond         1423 non-null object
BsmtExposure     1422 non-null object
BsmtFinType1     1423 non-null object
BsmtFinSF1       1460 non-null int64
BsmtFinType2     1422 non-null object
BsmtFinSF2       1460 non-null int64
BsmtUnfSF        1460 non-null int64
TotalBsmtSF      1460 non-null int64
Heating          1460 non-null object
HeatingQC        1460 non-null object
CentralAir       1460 non-null object
Electrical       1459 non-null object
1stFlrSF         1460 non-null int64
2ndFlrSF         1460 non-null int64
LowQualFinSF     1460 non-null int64
GrLivArea        1460 non-null int64
BsmtFullBath     1460 non-null int64
BsmtHalfBath     1460 non-null int64
FullBath         1460 non-null int64
HalfBath         1460 non-null int64
BedroomAbvGr     1460 non-null int64
KitchenAbvGr     1460 non-null int64
KitchenQual      1460 non-null object
TotRmsAbvGrd     1460 non-null int64
Functional       1460 non-null object
Fireplaces       1460 non-null int64
FireplaceQu      770 non-null object
GarageType       1379 non-null object
GarageYrBlt      1379 non-null float64
GarageFinish     1379 non-null object
GarageCars       1460 non-null int64
GarageArea       1460 non-null int64
GarageQual       1379 non-null object
GarageCond       1379 non-null object
PavedDrive       1460 non-null object
WoodDeckSF       1460 non-null int64
OpenPorchSF      1460 non-null int64
EnclosedPorch    1460 non-null int64
3SsnPorch        1460 non-null int64
ScreenPorch      1460 non-null int64
PoolArea         1460 non-null int64
PoolQC           7 non-null object
Fence            281 non-null object
MiscFeature      54 non-null object
MiscVal          1460 non-null int64
MoSold           1460 non-null int64
YrSold           1460 non-null int64
SaleType         1460 non-null object
SaleCondition    1460 non-null object
SalePrice        1460 non-null int64
dtypes: float64(3), int64(34), object(43)
memory usage: 912.6+ KB

In [5]:
train_data.columns

Index(['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street', 'Alley',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrType', 'MasVnrArea',
       'ExterQual', 'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', 'Heating', 'HeatingQC',
       'CentralAir', 'Electrical', '1stFlrSF', '2ndFlrSF', 'LowQualFinSF',
       'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath', 'HalfBath',
       'BedroomAbvGr', 'KitchenAbvGr', 'KitchenQual', 'TotRmsAbvGrd',
       'Functional', 'Fireplaces', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual', 'GarageCond',
       'PavedDrive', 'WoodDeckSF', 'OpenPorchSF', 'EnclosedPorch', '3SsnPorch',
       'ScreenPorch', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition', 'SalePrice'],
      dtype='object')

In [6]:
data_columns = [x for x in train_data.columns]
data_columns = pd.Series(data_columns)
data_columns

0        MSSubClass
1          MSZoning
2       LotFrontage
3           LotArea
4            Street
5             Alley
6          LotShape
7       LandContour
8         Utilities
9         LotConfig
10        LandSlope
11     Neighborhood
12       Condition1
13       Condition2
14         BldgType
15       HouseStyle
16      OverallQual
17      OverallCond
18        YearBuilt
19     YearRemodAdd
20        RoofStyle
21         RoofMatl
22      Exterior1st
23      Exterior2nd
24       MasVnrType
25       MasVnrArea
26        ExterQual
27        ExterCond
28       Foundation
29         BsmtQual
          ...
50     BedroomAbvGr
51     KitchenAbvGr
52      KitchenQual
53     TotRmsAbvGrd
54       Functional
55       Fireplaces
56      FireplaceQu
57       GarageType
58      GarageYrBlt
59     GarageFinish
60       GarageCars
61       GarageArea
62       GarageQual
63       GarageCond
64       PavedDrive
65       WoodDeckSF
66      OpenPorchSF
67    EnclosedPorch
68        3SsnPorch
69      ScreenPorch
70         PoolArea
71           PoolQC
72            Fence
73      MiscFeature
74          MiscVal
75           MoSold
76           YrSold
77         SaleType
78    SaleCondition
79        SalePrice
Length: 80, dtype: object

In [7]:
null_values_count = [len(train_data[train_data[x].isnull()==True]) for x in data_columns]
null_values_count = pd.Series(null_values_count)
null_values_count

0        0
1        0
2      259
3        0
4        0
5     1369
6        0
7        0
8        0
9        0
10       0
11       0
12       0
13       0
14       0
15       0
16       0
17       0
18       0
19       0
20       0
21       0
22       0
23       0
24       8
25       8
26       0
27       0
28       0
29      37
      ...
50       0
51       0
52       0
53       0
54       0
55       0
56     690
57      81
58      81
59      81
60       0
61       0
62      81
63      81
64       0
65       0
66       0
67       0
68       0
69       0
70       0
71    1453
72    1179
73    1406
74       0
75       0
76       0
77       0
78       0
79       0
Length: 80, dtype: int64

In [8]:
null_values = pd.concat([data_columns, null_values_count], axis=1)
null_values

                0     1
0      MSSubClass     0
1        MSZoning     0
2     LotFrontage   259
3         LotArea     0
4          Street     0
5           Alley  1369
6        LotShape     0
7     LandContour     0
8       Utilities     0
9       LotConfig     0
10      LandSlope     0
11   Neighborhood     0
12     Condition1     0
13     Condition2     0
14       BldgType     0
15     HouseStyle     0
16    OverallQual     0
17    OverallCond     0
18      YearBuilt     0
19   YearRemodAdd     0
20      RoofStyle     0
21       RoofMatl     0
22    Exterior1st     0
23    Exterior2nd     0
24     MasVnrType     8
25     MasVnrArea     8
26      ExterQual     0
27      ExterCond     0
28     Foundation     0
29       BsmtQual    37
..            ...   ...
50   BedroomAbvGr     0
51   KitchenAbvGr     0
52    KitchenQual     0
53   TotRmsAbvGrd     0
54     Functional     0
55     Fireplaces     0
56    FireplaceQu   690
57     GarageType    81
58    GarageYrBlt    81
59   GarageFinish    81
60     GarageCars     0
61     GarageArea     0
62     GarageQual    81
63     GarageCond    81
64     PavedDrive     0
65     WoodDeckSF     0
66    OpenPorchSF     0
67  EnclosedPorch     0
68      3SsnPorch     0
69    ScreenPorch     0
70       PoolArea     0
71         PoolQC  1453
72          Fence  1179
73    MiscFeature  1406
74        MiscVal     0
75         MoSold     0
76         YrSold     0
77       SaleType     0
78  SaleCondition     0
79      SalePrice     0

[80 rows x 2 columns]

In [14]:
null_values_table = null_values.loc[null_values[1] > 0].sort_values(by=1, ascending=False)
null_values_table

               0     1
71        PoolQC  1453
73   MiscFeature  1406
5          Alley  1369
72         Fence  1179
56   FireplaceQu   690
2    LotFrontage   259
62    GarageQual    81
57    GarageType    81
58   GarageYrBlt    81
63    GarageCond    81
59  GarageFinish    81
31  BsmtExposure    38
34  BsmtFinType2    38
32  BsmtFinType1    37
30      BsmtCond    37
29      BsmtQual    37
25    MasVnrArea     8
24    MasVnrType     8
41    Electrical     1

In [15]:
len(null_values_table)

19